# Generated by Django 2.1.5 on 2019-03-06 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='NewsPost',
        ),
    ]
