# Generated by Django 2.1.5 on 2019-03-05 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190209_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='money',
            field=models.IntegerField(default=10000),
        ),
        migrations.AddField(
            model_name='profile',
            name='stock_possesed_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='stock_possesed_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='stock_possesed_4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='stock_possesed_5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='stock_possesed_6',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='stock_possesed_7',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='stock_possesed_8',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='stock_possesed_9',
            field=models.IntegerField(default=0),
        ),
    ]
