# Generated by Django 2.1.5 on 2019-03-05 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190305_1818'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='stock_possesed_1',
            new_name='BHEL_stock',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='stock_possesed_2',
            new_name='BajajAllianz_stock',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='stock_possesed_3',
            new_name='GSKPfizer_stock',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='stock_possesed_4',
            new_name='JPMorgan_stock',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='stock_possesed_5',
            new_name='Nestle_stock',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='stock_possesed_6',
            new_name='Nissan_stock',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='stock_possesed_7',
            new_name='SunPharma_stock',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='stock_possesed_8',
            new_name='TataMotors_stock',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='stock_possesed_9',
            new_name='Tesla_stock',
        ),
    ]
