# Generated by Django 2.1.5 on 2019-03-07 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190305_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='APInfovault_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='Bayer_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='Cogitare_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='Credit_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='Crystal_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='Exxon_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='Heralded_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='Soteria_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='Uncash_stock',
            field=models.IntegerField(default=0),
        ),
    ]
