# Generated by Django 3.0.2 on 2020-01-23 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190307_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='money_possesed',
            field=models.FloatField(default=1000),
        ),
    ]
