# Generated by Django 2.1.5 on 2019-02-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('opening_price', models.IntegerField()),
                ('current_price', models.IntegerField()),
                ('percentage_change', models.IntegerField()),
                ('day_high', models.IntegerField()),
                ('day_low', models.IntegerField()),
            ],
        ),
    ]
