# Generated by Django 2.1.5 on 2019-02-09 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_price', '0002_remove_company_percentage_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='percentage_change',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='company',
            name='current_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='company',
            name='day_high',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='company',
            name='day_low',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='company',
            name='opening_price',
            field=models.IntegerField(default=0),
        ),
    ]
