# Generated by Django 2.1.5 on 2019-03-05 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_price', '0004_auto_20190305_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForBuy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
    ]
